package com.tweetapp.userservice.bean;

import java.util.ArrayList;
import java.util.List;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBMapperFieldModel.DynamoDBAttributeType;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTyped;

import lombok.Data;
import lombok.Getter;
import lombok.Setter;

/**
 * @author Nithya T
 *
 */

@DynamoDBTable(tableName = "user")
public class User {
	
	@DynamoDBHashKey(attributeName = "_id")
	@DynamoDBAutoGeneratedKey
	private String _id;
	@DynamoDBAttribute(attributeName = "loginId")
	private String loginId;
	@DynamoDBAttribute(attributeName = "firstName")
	private String firstName;
	@DynamoDBAttribute(attributeName = "lastName")
	private String lastName;
	@DynamoDBAttribute(attributeName = "emailId")
	private String emailId;
	@DynamoDBAttribute(attributeName = "phnNum")
	private String phnNum;
	@DynamoDBAttribute(attributeName = "password")
	private String password;
	@DynamoDBTyped(DynamoDBAttributeType.BOOL)
	@DynamoDBAttribute(attributeName = "isLogIn")
	private boolean isLogIn;
	@DynamoDBAttribute(attributeName = "role")
	private List<String> role = new ArrayList<>();

	public String get_id() {
		return _id;
	}
	public void set_id(String _id) {
		this._id = _id;
	}
	public String getLoginId() {
		return loginId;
	}
	public void setLoginId(String loginId) {
		this.loginId = loginId;
	}
	public String getFirstName() {
		return firstName;
	}
	public void setFirstName(String firstName) {
		this.firstName = firstName;
	}
	public String getLastName() {
		return lastName;
	}
	public void setLastName(String lastName) {
		this.lastName = lastName;
	}
	public String getEmailId() {
		return emailId;
	}
	public void setEmailId(String emailId) {
		this.emailId = emailId;
	}
	public String getPhnNum() {
		return phnNum;
	}
	public void setPhnNum(String phnNum) {
		this.phnNum = phnNum;
	}
	public String getPassword() {
		return password;
	}
	public void setPassword(String password) {
		this.password = password;
	}
	public boolean isLogIn() {
		return isLogIn;
	}
	public void setLogIn(boolean isLogIn) {
		this.isLogIn = isLogIn;
	}
	public List<String> getRole() {
		return role;
	}
	public void setRole(List<String> role) {
		this.role = role;
	}
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((_id == null) ? 0 : _id.hashCode());
		result = prime * result + ((loginId == null) ? 0 : loginId.hashCode());
		return result;
	}
	@Override
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (getClass() != obj.getClass())
			return false;
		User other = (User) obj;
		if (_id == null) {
			if (other._id != null)
				return false;
		} else if (!_id.equals(other._id))
			return false;
		if (loginId == null) {
			if (other.loginId != null)
				return false;
		} else if (!loginId.equals(other.loginId))
			return false;
		return true;
	}
	@Override
	public String toString() {
		return "User [_id=" + _id + ", loginId=" + loginId + ", firstName=" + firstName + ", lastName=" + lastName
				+ ", emailId=" + emailId + ", phnNum=" + phnNum + ", password=" + password + ", isLogIn=" + isLogIn
				+ ", role=" + role + "]";
	}

	
}
